ext_if = "em0"
vpn_if = "wg0"
vpn_net = "10.200.200.0/24"

scrub in all fragment reassemble

nat on $ext_if from $vpn_net to any -> ($ext_if)

rdr on $vpn_if proto udp from $vpn_net to any port 53 -> 127.0.0.1 port 53
rdr on $vpn_if proto tcp from $vpn_net to any port 53 -> 127.0.0.1 port 53
rdr on lo0 proto udp from any to 10.200.200.1 port 53 -> 127.0.0.1 port 53
rdr on lo0 proto tcp from any to 10.200.200.1 port 53 -> 127.0.0.1 port 53

pass all
block out on $ext_if proto { udp tcp } from $vpn_net to any port 53
